### ISSUE TITLE
Docker fop start

### ISSUE THREAD

**Issue by StephanKrauss** [chrwahl/docker-fop#1]
Hello,

i'm a beginner in docker.
I need a simple example for using docker-fop.

Can you help with a simple example ?

Your sincerly

Stephan

**Comment by chrwahl** [comment]
Hi @StephanKrauss 

Thank you for reminding me that I should write an example. I now updated the README.md file with a guide and some examples.

I hope that it helps. Allow me also to refer to the [getting started guide](https://docs.docker.com/get-started/) for Docker.

Kind regards
Christian Wahl
